//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityOWIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Id { get; set; }
        public System.TimeSpan Arrival_time { get; set; }
        public Nullable<System.TimeSpan> Departure_time { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Type { get; set; }
    }
}
